FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Declare build args so Railway passes env vars to Vite at build time
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_SERVICE_KEY
ARG VITE_ADMIN_SECRET
ARG VITE_SUPERADMIN_SECRET
ARG VITE_BREVO_API_KEY
ARG VITE_APP_URL

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_SERVICE_KEY=$VITE_SUPABASE_SERVICE_KEY
ENV VITE_ADMIN_SECRET=$VITE_ADMIN_SECRET
ENV VITE_SUPERADMIN_SECRET=$VITE_SUPERADMIN_SECRET
ENV VITE_BREVO_API_KEY=$VITE_BREVO_API_KEY
ENV VITE_APP_URL=$VITE_APP_URL

RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist
COPY server.js ./
EXPOSE 3000
CMD node server.js
