FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Declare build args so Railway passes env vars to Vite at build time
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPABASE_SERVICE_KEY
ARG VITE_ADMIN_SECRET
ARG VITE_SUPERADMIN_SECRET
ARG VITE_BREVO_API_KEY
ARG VITE_APP_URL
ARG VITE_ASSISTANT_TOKEN
# Server-side runtime env vars worden direct door Railway geïnjecteerd
# (ANTHROPIC_API_KEY, ASSISTANT_TOKEN, ASSISTANT_TENANT_ID, ASSISTANT_MODEL,
#  GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI, BREVO_API_KEY).
# Deze hoeven niet in de Vite-build.

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPABASE_SERVICE_KEY=$VITE_SUPABASE_SERVICE_KEY
ENV VITE_ADMIN_SECRET=$VITE_ADMIN_SECRET
ENV VITE_SUPERADMIN_SECRET=$VITE_SUPERADMIN_SECRET
ENV VITE_BREVO_API_KEY=$VITE_BREVO_API_KEY
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_ASSISTANT_TOKEN=$VITE_ASSISTANT_TOKEN

RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install --omit=dev
COPY --from=build /app/dist ./dist
COPY server.js ./
COPY server ./server
EXPOSE 3000
CMD node server.js
